Update .travis.yml and package.json#engines.node
emberjs/ember-render-modifiers pull request #28
Opened 2020-10-19 03:17 UTC by NullVoxPopuli

BREAKING CHANGE: drop support for node 6 and 8

2020-10-19 11:39 UTC, rwjblue requested changes

2020-10-19 11:39 UTC, rwjblue commented on package.json
> +    "node": "10.* || >= 12"
```suggestion
    "node": "10.* || 12.* || >= 14"
```

2020-10-19 11:39 UTC, rwjblue commented on package.json
> +    "node": "10.* || >= 12"
Node 13 is EOL

2021-10-01 03:03 UTC, SergeAstapov commented
This is now superseded by #40 and #46

2021-10-01 11:51 UTC, closed without merging